import { StakePool } from "./types";

export const MOCK_POOLS: StakePool[] = [
  {
    id: "jito",
    name: "Jito",
    lstTicker: "JitoSOL",
    program: "spl-stake-pool",
    activeSolStaked: 12788407,
    validatorCount: 325,
    medianApy: 5.97,
    networkHealthScore: 68,
    scores: {
      smallValidatorBias: 55,
      selfDealing: 90,
      mevSandwichPolicy: 75,
      nakamotoImpact: 60,
      validatorSetSize: 95,
      geographicDiversity: 70,
      commissionDiscipline: 80,
      transparency: 85,
    },
  },
  {
    id: "doublezero",
    name: "DoubleZero",
    lstTicker: "dzSOL",
    program: "spl-stake-pool",
    activeSolStaked: 13357851,
    validatorCount: 318,
    medianApy: 5.62,
    networkHealthScore: 62,
    scores: {
      smallValidatorBias: 50,
      selfDealing: 70,
      mevSandwichPolicy: 80,
      nakamotoImpact: 55,
      validatorSetSize: 93,
      geographicDiversity: 65,
      commissionDiscipline: 70,
      transparency: 60,
    },
  },
  {
    id: "blazestake",
    name: "BlazeStake",
    lstTicker: "bSOL",
    program: "spl-stake-pool",
    activeSolStaked: 1031679,
    validatorCount: 234,
    medianApy: 5.72,
    networkHealthScore: 78,
    scores: {
      smallValidatorBias: 82,
      selfDealing: 95,
      mevSandwichPolicy: 85,
      nakamotoImpact: 75,
      validatorSetSize: 88,
      geographicDiversity: 72,
      commissionDiscipline: 75,
      transparency: 80,
    },
  },
  {
    id: "jpool",
    name: "JPool",
    lstTicker: "JSOL",
    program: "spl-stake-pool",
    activeSolStaked: 1250759,
    validatorCount: 217,
    medianApy: 5.78,
    networkHealthScore: 74,
    scores: {
      smallValidatorBias: 75,
      selfDealing: 90,
      mevSandwichPolicy: 80,
      nakamotoImpact: 70,
      validatorSetSize: 85,
      geographicDiversity: 68,
      commissionDiscipline: 72,
      transparency: 75,
    },
  },
  {
    id: "phase",
    name: "Phase Delegate",
    lstTicker: "pdSOL",
    program: "spl-stake-pool",
    activeSolStaked: 1068321,
    validatorCount: 163,
    medianApy: 5.68,
    networkHealthScore: 88,
    scores: {
      smallValidatorBias: 95,
      selfDealing: 100,
      mevSandwichPolicy: 90,
      nakamotoImpact: 88,
      validatorSetSize: 78,
      geographicDiversity: 80,
      commissionDiscipline: 82,
      transparency: 85,
    },
  },
  {
    id: "vault",
    name: "Vault",
    lstTicker: "vSOL",
    program: "spl-stake-pool",
    activeSolStaked: 1249140,
    validatorCount: 121,
    medianApy: 5.82,
    networkHealthScore: 35,
    scores: {
      smallValidatorBias: 45,
      selfDealing: 10,
      mevSandwichPolicy: 60,
      nakamotoImpact: 40,
      validatorSetSize: 65,
      geographicDiversity: 50,
      commissionDiscipline: 30,
      transparency: 25,
    },
  },
  {
    id: "dynosol",
    name: "dynoSOL",
    lstTicker: "dynoSOL",
    program: "spl-stake-pool",
    activeSolStaked: 523576,
    validatorCount: 76,
    medianApy: 5.81,
    networkHealthScore: 65,
    scores: {
      smallValidatorBias: 70,
      selfDealing: 85,
      mevSandwichPolicy: 65,
      nakamotoImpact: 60,
      validatorSetSize: 55,
      geographicDiversity: 58,
      commissionDiscipline: 68,
      transparency: 50,
    },
  },
  {
    id: "jagpool",
    name: "JagPool",
    lstTicker: "jagSOL",
    program: "spl-stake-pool",
    activeSolStaked: 744077,
    validatorCount: 75,
    medianApy: 5.75,
    networkHealthScore: 80,
    scores: {
      smallValidatorBias: 85,
      selfDealing: 95,
      mevSandwichPolicy: 78,
      nakamotoImpact: 80,
      validatorSetSize: 55,
      geographicDiversity: 90,
      commissionDiscipline: 75,
      transparency: 70,
    },
  },
  {
    id: "stke",
    name: "STKE",
    lstTicker: "STKESOL",
    program: "spl-stake-pool",
    activeSolStaked: 689479,
    validatorCount: 66,
    medianApy: 5.75,
    networkHealthScore: 62,
    scores: {
      smallValidatorBias: 65,
      selfDealing: 80,
      mevSandwichPolicy: 60,
      nakamotoImpact: 58,
      validatorSetSize: 50,
      geographicDiversity: 55,
      commissionDiscipline: 65,
      transparency: 55,
    },
  },
  {
    id: "marinade",
    name: "Marinade",
    lstTicker: "mSOL",
    program: "marinade",
    activeSolStaked: 2888186,
    validatorCount: 57,
    medianApy: 5.86,
    networkHealthScore: 52,
    scores: {
      smallValidatorBias: 50,
      selfDealing: 75,
      mevSandwichPolicy: 30,
      nakamotoImpact: 55,
      validatorSetSize: 45,
      geographicDiversity: 60,
      commissionDiscipline: 70,
      transparency: 65,
    },
  },
  {
    id: "shinobi",
    name: "Shinobi",
    lstTicker: "xSHIN",
    program: "spl-stake-pool",
    activeSolStaked: 1096471,
    validatorCount: 55,
    medianApy: 5.65,
    networkHealthScore: 66,
    scores: {
      smallValidatorBias: 60,
      selfDealing: 85,
      mevSandwichPolicy: 75,
      nakamotoImpact: 62,
      validatorSetSize: 45,
      geographicDiversity: 60,
      commissionDiscipline: 78,
      transparency: 70,
    },
  },
  {
    id: "edgevana",
    name: "Edgevana",
    lstTicker: "edgeSOL",
    program: "spl-stake-pool",
    activeSolStaked: 828375,
    validatorCount: 48,
    medianApy: 5.75,
    networkHealthScore: 48,
    scores: {
      smallValidatorBias: 40,
      selfDealing: 50,
      mevSandwichPolicy: 70,
      nakamotoImpact: 45,
      validatorSetSize: 40,
      geographicDiversity: 35,
      commissionDiscipline: 72,
      transparency: 60,
    },
  },
  {
    id: "definity",
    name: "Definity",
    lstTicker: "definSOL",
    program: "sanctum-multi",
    activeSolStaked: 261604,
    validatorCount: 25,
    medianApy: 5.78,
    networkHealthScore: 72,
    scores: {
      smallValidatorBias: 78,
      selfDealing: 90,
      mevSandwichPolicy: 75,
      nakamotoImpact: 70,
      validatorSetSize: 30,
      geographicDiversity: 85,
      commissionDiscipline: 70,
      transparency: 65,
    },
  },
  {
    id: "indiesol",
    name: "IndieSOL",
    lstTicker: "IndieSOL",
    program: "spl-stake-pool",
    activeSolStaked: 974,
    validatorCount: 22,
    medianApy: 6.53,
    networkHealthScore: 70,
    scores: {
      smallValidatorBias: 88,
      selfDealing: 95,
      mevSandwichPolicy: 65,
      nakamotoImpact: 65,
      validatorSetSize: 28,
      geographicDiversity: 55,
      commissionDiscipline: 70,
      transparency: 60,
    },
  },
];
